### ISSUE TITLE
Please allow 3rd party launchers to download this mod

### ISSUE THREAD

**Issue by totoltetl** [ErrorMikey/KubeUtils#1]
It would be great if you could allow 3rd party launchers to download this mod from curseforge - having to manually install it is very annoying.

related: https://github.com/ErrorMikey/JustHammers/issues/2 https://github.com/ErrorMikey/AcceleratedDecay/issues/1

**Comment by Su5eD** [comment]
+1. This mod is even licensed under the GPL. Why are 3rd party downloads disabled then? What is the purpose of making it open source?

**Comment by MichaelHillcox** [comment]
Fixed (I think)
